runtime: nodejs10
service: corvid-firestore-connector

instance_class: F4_1G

env_variables:
  SECRET_KEY: someNEwSecret
  ALLOWED_OPERATIONS: '["get", "find", "count", "update", "insert", "remove"]'  
